[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

# Proxy all /api/* from the Next app to your Cloud Run backend
[[redirects]]
from = "/api/*"
to = "https://searchsphere-backend-527375959391.us-central1.run.app/api/:splat"
status = 200
force = true
